server:
  port: 8085
  servlet:
    session:
      tracking-modes: cookie

spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 2400024
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis
  redis:
    url: redis://127.0.0.1:6379

jwt:
  key: t911ur00
  expirationDay: 1