name: deploy-prod
run-name: ${{ github.actor }} is deploy prod
on: [push]
jobs:
  main-job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: 'install java'
        run: sudo apt install openjdk-17-jdk openjdk-17-jre

      - name: 'install maven'
        run: sudo apt install maven

      - name: 'build jar file'
        run: mvn package

      - name: 'show structure'
        run: ls -al

      - name: 'delete old jar file'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: '62.217.182.204'
          username: 'root'
          password: 'CZnYq55w%VuA'
          port: '22'
          script: |
            cd ../../var/www/back/target
            sudo kill -9 `sudo lsof -t -i:8085`
            sudo rm ./*.jar
#
      - name: 'deploy'
        uses: appleboy/scp-action@v0.1.4
        with:
          host: '62.217.182.204'
          username: 'root'
          password: 'CZnYq55w%VuA'
          port: '22'
          source: 'target/*.jar'
          target: '../../var/www/back'
#
      - name: 'start-remote-command'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: '62.217.182.204'
          username: 'root'
          password: 'CZnYq55w%VuA'
          port: '22'
          script: |
            cd ../../var/www/back/target
            screen -m -d java -jar ClientWeb-0.0.1-SNAPSHOT.jar --spring.config.name=application-dev
            ls -al
